### ISSUE TITLE
How to get device disconnect event

### ISSUE THREAD

**Issue by ViramPurohit** [opendroneid/receiver-android#102]
I want to know device disconnect callback or event but not getting any callback.

**Comment by friissoren** [comment]
Sorry, I don't really understand what you are looking for. Nothing in the application connects to anything, so there will not be any disconnect events.

**Comment by gabrielcox** [comment]
Adding to Soren's comment.  Remote ID is only 1 way broadcasts sent by the unmanned aircraft.  The receiver simply "listens" to the broadcasts to show the aircraft.  Since there are no actual (2-way) "connections".  

The only way to handle an aircraft out of range is that the receiver is no longer getting the broadcasts.

**Comment by friissoren** [comment]
Maybe related to this, there are already these feature requests open: #4 and #27.
