### ISSUE TITLE
Coded PHY is not supported by Google Pixel 6, 7 series

### ISSUE THREAD

**Issue by prateekn9** [opendroneid/receiver-android#108]
When tested for Bluetooth Long range beacon using nrf Scanner, Google pixel 6, 6a, 7, 7 pro cannot scan long range beacons.

**Comment by janusw** [comment]
The Pixel 6 is already in the list of supported smartphones. When I tested it two years ago (with Android 12), WiFi Beacon and WiFi NAN both worked well, but BLE5 LR was not supported (see PR #39).

It's quite plausible that the Pixel 7 supports the same set of features, although it's a bit disappointing that Google would still not support BLE5 LR in its flagship phone (Samsung obviously does a better job there, providing solid BLE5 support since the S10).

@prateekn9 If you test all the features of the Pixel 7 (Pro), as described in https://github.com/opendroneid/receiver-android/blob/master/supported-smartphones.md#testing-methodology, you could open a PR to add it to the list.

Also, if someone has the Pixel 8 at their disposal, it would be interesting to know how it is doing wrt BLE5.

**Comment by janusw** [comment]
> Also, if someone has the Pixel 8 at their disposal, it would be interesting to know how it is doing wrt BLE5.

I actually got my hands on a Pixel 8 (Pro!) recently, and it seems the situation is still the same as with the Pixel 6: It claims to support Coded PHY and Extended Advertising, but I don't actually receive any BLE5 extended advertisements, only basic BLE4 stuff. Shame on you, Google! 😭

**Comment by janusw** [comment]
> Ok. Thanks. I assume you were intending to get this information added to the list of smartphones? https://github.com/opendroneid/receiver-android/blob/master/supported-smartphones.md

The list has been updated via #114, so I think this issue can be closed.
