### ISSUE TITLE
maximum receiving distance

### ISSUE THREAD

**Issue by maiermic** [opendroneid/receiver-android#23]
I am curious up to what distance, the [various smartphones](https://github.com/opendroneid/receiver-android/blob/master/supported-smartphones.md#list-of-devices-and-their-capabilities) receive a (stable) signal. I guess, there are big differences. The same goes for the other direction, i.e. how far each smartphone can send data.

**Comment by friissoren** [comment]
There is no clear answer to that question, since it depends on a multitude of things:
* Transmit power of the transmitter
* Transmit antenna implementation
* Transmit method (BT4, BT5 Long Range, Wi-Fi)
* Unobstructed (or not) line of sight between transmitter and receiver
* General noise interference in the 2.4 GHz band (or 5 GHz)
* Receiver antenna efficiency
* Receiver noise filtering before decoding

In general, BT5 Long Range Coded PHY S=8 will be picked up at a further distance than BT4, due to the Forward Error Correction on the Coded PHY (the S=8 sort of indicates that the information is transmitted 8 times with different error encoding included).

Typically, Wi-Fi will have even longer range than BT5, since Wi-Fi is allowed to transmit at 20 dBm vs. 10 dBm for Bluetooth. This is in Europe. The US have even higher limits but in praxis I think also in the US those are the limits typically followed.

**Comment by maiermic** [comment]
I agree that there may be no absolute measure. Nevertheless, I'm curious up to what distance it worked when you tested. I haven't found any number yet and I don't have a smartphone with BT5 Long Range support to perform any measurements myself. I won't blame you if I don't get it working up to the same distance if/after I bought the same device :wink: 

> Anything is better than nothing

**Comment by friissoren** [comment]
Some kind of guidance on distance given below but please keep in mind that there can be very big variations for both the better and the worse for these, depending on all the factors listed earlier. Also, the reception rate is also a clear part of this since you can never expect to receive every single ping sent from the transmitter but where is the limit on how many you allow to "drop"? Receiving one per 10 second or whatever might for some situations be okay.

BT4: 200 - 250 m. I have heard reports of 500 m also
BT5: ~1 km
Wi-Fi ~1 - 2 km

**Comment by maiermic** [comment]
I guess, ~1 km with BT5 is a generic estimation of the technology in general and not with a smartphone you can buy today. I usually expect a regular Wi-Fi setup only to cover around ca. 150 m. There may be special equipment (e.g. directional antennas) to get it working at a larger distance, but does this work with a smartphone or/and a mobile/portable access point (powered by an akku)? IMO 1-2 km may be possible (in theory), but I don't think it can be achieved with a regular smartphone.

I'm more interested in your personal experience. Up to which distance did you test or use OpenDroneID with your BT5 LR setup (e.g. smartphone)? What distance do you expect in practice on an open field with a moving target?

**Comment by friissoren** [comment]
We have measured somehow reasonably reception rate for BT5 transmissions  at 1.2 km. This was from a CC2640 transmitter where the transmit antenna is just a simple trace on one side of the PCB and received by a Samsung Galaxy S10 phone. Since the CC2640 is limited to 5 dBm transmit power, going to the maximum allowed would only improve on this.

I have heard of WiFi NaN reception claims up to 3-4 km.

Don't try to extrapolate experience with BT and WiFi from indoor environments to the outdoors drone ID relevant conditions. Keywords here are *non-obstructed line of sight with no interference* and the transmitter lifted off the ground. The receiver is held in the hand as you would normally when standing. Also, I am not talking about transmitting from a smartphone.

**Comment by lukasbrchl** [comment]
Hi @maiermic, as Soren explained it is a very complex and unexplored topic. We plan to do some thorough testing with the help of one university lab in the US. We will be doing range tests with various TX powers and message frequencies. 

From our experience, I can tell you that it is possible to achieve 500m on 8 dBm TX power in the city with BT5 LR and a little less range with BT4 - transmitting from IoT device with internal antenna and receiving with OnePlus 8T. In unobstructed terrain, we have been able to receive messages from up to 1km, but I'm not confident about TX power on the device in this case.

Also please note,  that each manufacturer of drone/add-on claims different numbers :)

**Comment by maiermic** [comment]
Thank you very much. I'm really looking forward to see your test results. Do you also plan to test smartphones as transmitters? Do you know, how to find out the TX power of a smartphone?

**Comment by lukasbrchl** [comment]
From our side, no plan to do that as I don't see any added value of transmitting Remote ID from smartphones. But AFAIK, you can set maximum tx power +1 dBm in nRF Connect as discussed in #16. It is however a little more complicated because each of the smartphones has a different RF setup for BT/WiFi. The internal antennas, their placement and orientation plays a key role in the TX range.

**Comment by maiermic** [comment]
As you said

> it is a very complex and unexplored topic.

OpenDroneID is the first project I found that uses BT5 LR on smartphones. IMO you are pioneers :wink: 

I am simply interested in what is possible with current technology. In general, BT5 projects are likely to use a smartphone for display or as a controller for a BT5 device. Therefore, it is important to know how well 2-way communication works and what the limitations are.

I think I read somewhere (some time ago) that some smartphones with BT5 LR do not work better than BT4. Of course, it may be that wrong implementation/testing led to this statement or that this is outdated because the manufacturer has improved the device drivers, etc. In any case, your [list](https://github.com/opendroneid/receiver-android/blob/master/supported-smartphones.md#list-of-devices-and-their-capabilities) shows very well that there are very large differences in the BT5 LR support of the smartphones.

I really appreciate that you share your experience with the public :blush:

**Comment by friissoren** [comment]
I start to understand the disconnect here :-) I thought you initially were asking from a drone ID perspective but your concern is more on the usage of BT5 LR etc. between phones. These two use cases are very different and will perform very differently for the reasons described in this discussion.

Simple one-way squirts from a transmitter using close to maximum power and located high in the air will be possible to pick-up at much much longer distances than 2-way communication between phones on the ground using significantly less than maximum transmission power and being obstructed by all the walls, trees and what-not that most likely will be between the two devices.

But I am glad that we got these things written down and clarified. Hopefully this discussion will be useful to someone else visiting this project.

**Comment by maiermic** [comment]
> I thought you initially were asking from a drone ID perspective but your concern is more on the usage of BT5 LR etc. between phones.

Kind of both :sweat_smile: I'm most interested in usage of BT5 LR between a phone and another device. I have been made aware of the drone ID project by @lukasbrchl [post](https://devzone.nordicsemi.com/f/nordic-q-a/33060/is-there-any-smartphone-with-supporting-of-bluetooth-5-long-range-feature/290346#290346) in the Nordic DevZone forum. Thanks. I'm sure this information is useful for many people interested in this project or the technology itself :grin:
