### ISSUE TITLE
Coordinates with Latitude < 0 and Longitude < 0 are ignored

### ISSUE THREAD

**Issue by kshahar** [opendroneid/receiver-android#6]
See here -
https://github.com/opendroneid/receiver-android/blob/247daf62429772949d752ec969c5db51567d7b87/Android/app/src/main/java/org/opendroneid/android/data/LocationData.java#L122
https://github.com/opendroneid/receiver-android/blob/247daf62429772949d752ec969c5db51567d7b87/Android/app/src/main/java/org/opendroneid/android/data/LocationData.java#L136

Instead of < 0 it should be latitude < -90 and longitude < -180 I assume?

**Comment by friissoren** [comment]
Sorry, that is a mistake on my behalf. Clearly needs to be fixed so that latitude is -90 -> 90 and longitude is -180 -> 180.
I now see that there is a problem with this also in the opendroneid-core-c code:
https://github.com/opendroneid/opendroneid-core-c/blob/master/libopendroneid/opendroneid.h#L39
Thanks for reporting.

**Comment by friissoren** [comment]
Fix pushed to master. If there are still problems, please let me know.
