### ISSUE TITLE
What is the license of this source?

### ISSUE THREAD

**Issue by muramura** [opendroneid/receiver-android#66]
The source license published on GitHUB is defined at the following URL.

However, without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work.

I wish this source was open source and under the APACHE-2.0 license.

Please install the license. 

https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository#choosing-the-right-license

**Comment by friissoren** [comment]
The sources are already under the Apache-2.0 license:
https://github.com/opendroneid/receiver-android/tree/master/Legal_notices

See also the header of the various source files.

Maybe because the LICENSE file is not located at the root of the project, Github doesn't pick up that and thus doesn't show it in the About field. I could probably make a duplicate file there.

**Comment by friissoren** [comment]
Fixed now.
