### ISSUE TITLE
Download this app from Google Play ?

### ISSUE THREAD

**Issue by muramura** [opendroneid/receiver-android#71]
In Japan, after June 20, 2022, you are obliged to report your remote ID when you register your aircraft.
I think this app can be downloaded from Google Play so that drone users and managers can easily use it.

**Comment by friissoren** [comment]
The Open Street Map version of the app is now available on the Google Playstore (enjoy :-)
https://play.google.com/store/apps/details?id=org.opendroneid.android_osm

With the above link you can get to it but for some reason, even when searching for the exact name of the app, it does not show up in the suggested results. I don't know if it is because it just today went live on the store or whether it needs to be download a certain amount of times before it starts showing up in the search results.

**Comment by djoris** [comment]
fwiw, it might be shadowbanned because #51 ? On my Android 13 phone, Google Play Store gives me: "This app isn't available for your device because it was made for an older version of Android".
![Screenshot_20231023_100450_Google](https://github.com/opendroneid/receiver-android/assets/790925/4942f757-e2a8-458c-964d-c54f722b202b)

Sorry if resurrecting a closed ticket wasn't the proper route.

**Comment by friissoren** [comment]
I suspect this is because the target API of the app has not been updated in a long time. I would have to update that and check any problems possibly occurring from that. 

However, at the moment I don't have any time to spend on this kind of activities, nor do I have any phone HW that is running Android 13 to test on. I am afraid I won't be able to fix this issue any time soon.

The full source codes are available. If someone is able to do the target API update and also test via local installation on an Android 13 phone that everything is working, I could try to find the time to do the update to the PlayStore.
